services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node:24_alpine_express
    container_name: container_node
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - PORT=3000
    networks:
      network_node:
        ipv4_address: 172.16.0.11

  database:
    image: postgres:17.5
    container_name: container_postgresql
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      network_node:
        ipv4_address: 172.16.0.12

  adminer:
    image: adminer:5-standalone
    container_name: container_adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      network_node:
        ipv4_address: 172.16.0.13

networks:
  network_node:
    name: global_node
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24